/oak:
# top level camera config
  camera_i_enable_imu: true
  camera_i_enable_ir: true
  camera_i_floodlight_brightness: 0.0
  camera_i_ip: ''
  camera_i_laser_dot_brightness: 800.0
  camera_i_mx_id: ''
  camera_i_pipeline_type: RGBD
  camera_i_usb_port_id: ''
  camera_i_usb_speed: SUPER_PLUS

# NN config
  camera_i_nn_type: none
  nn_i_nn_config_path: depthai_ros_driver/potato
  # nn_i_enable_passthrough: true

# IMU config
  imu_i_max_q_size: 1

# RGB cam config
  rgb_i_board_socket_id: 0
  rgb_i_calibration_file: ''
  rgb_i_enable_preview: false
  rgb_i_keep_preview_aspect_ratio: true
  rgb_i_preview_size: 400

  # 4056*3040
  # rgb_i_width: 4056
  # rgb_i_height: 3040

  # 3840*2160
  # rgb_i_width: 3840
  # rgb_i_height: 2160

  # potato
  rgb_i_width: 640
  rgb_i_height: 400


  rgb_i_interleaved: false
  rgb_i_fps: 30.0
  rgb_i_low_bandwidth: false
  rgb_i_low_bandwidth_quality: 10
  rgb_i_max_q_size: 1
  rgb_i_publish_topic: true
  # 5312X6000, 48_MP, 4000x3000, 5MP, 1200, 800, 13MP, 12MP, 4K, 1080, 1440X1080, 720
  rgb_i_resolution: '1080P'
  rgb_i_output_isp: true

  rgb_i_set_isp_scale: false
  rgb_i_isp_num: 2
  rgb_i_isp_den: 3

  rgb_r_exposure: 1000
  rgb_r_focus: 120
  rgb_r_set_man_focus: true
  rgb_r_iso: 800
  rgb_r_keep_preview_aspect_ratio: true
  rgb_r_set_man_exposure: false

  rgb_r_set_man_whitebalance: false
  rgb_r_whitebalance: 3300


# LEFT stereo cam config
  left_i_board_socket_id: 1
  left_i_calibration_file: ''
  left_i_fps: 30.0

  left_i_width: 1280
  left_i_height: 800
  left_i_resolution: '720P'

  left_i_low_bandwidth: false
  left_i_low_bandwidth_quality: 50
  left_i_max_q_size: 1
  left_i_preview_size: 300
  left_i_publish_topic: false
  left_i_set_isp_scale: false
  left_r_exposure: 1000
  left_r_focus: 1
  left_r_iso: 800
  left_r_keep_preview_aspect_ratio: true
  left_r_set_man_exposure: false
  left_r_set_man_focus: false
  left_r_set_man_whitebalance: false
  left_r_whitebalance: 3300

# RIGHT stereo cam config
  right_i_board_socket_id: 2
  right_i_calibration_file: ''
  right_i_fps: 30.0
  
  right_i_width: 1280
  right_i_height: 800
  right_i_resolution: '720P'
  
  right_i_low_bandwidth: false
  right_i_low_bandwidth_quality: 50
  right_i_max_q_size: 1
  right_i_preview_size: 300
  right_i_publish_topic: false
  right_i_set_isp_scale: false
  right_r_exposure: 1000
  right_r_focus: 1
  right_r_iso: 800
  right_r_keep_preview_aspect_ratio: true
  right_r_set_man_exposure: false
  right_r_set_man_focus: false
  right_r_set_man_whitebalance: false
  right_r_whitebalance: 3300

# DEPTH config.
  stereo_i_align_depth: true
  stereo_i_bilateral_sigma: 0
  stereo_i_board_socket_id: 0
  stereo_i_calibration_file: ''
  stereo_i_decimation_filter_decimation_factor: 1
  stereo_i_decimation_filter_decimation_mode: PIXEL_SKIPPING
  stereo_i_depth_filter_size: 5
  stereo_i_depth_preset: HIGH_ACCURACY
  stereo_i_enable_decimation_filter: false
  stereo_i_enable_distortion_correction: false
  stereo_i_enable_spatial_filter: false
  stereo_i_enable_temporal_filter: false
  stereo_i_enable_threshold_filter: false
  stereo_i_extended_disp: true
  
  stereo_i_width: 640
  stereo_i_height: 400
  stereo_i_low_bandwidth: false
  stereo_i_low_bandwidth_quality: 50
  stereo_i_lr_check: true
  stereo_i_lrc_threshold: 10
  stereo_i_max_q_size: 1
  stereo_i_rectify_edge_fill_color: 0
  stereo_i_spatial_filter_alpha: 0.5
  stereo_i_spatial_filter_delta: 20
  stereo_i_spatial_filter_hole_filling_radius: 2
  stereo_i_spatial_filter_iterations: 1
  stereo_i_stereo_conf_threshold: 255
  stereo_i_temporal_filter_alpha: 0.4
  stereo_i_temporal_filter_delta: 20
  stereo_i_temporal_filter_persistency: VALID_2_IN_LAST_4
  stereo_i_threshold_filter_max_range: 2000
  stereo_i_threshold_filter_min_range: 200
  